import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  scannerCard: {
    backgroundColor: Colors.white,
    borderRadius: 15,
    padding: 25,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 5,
  },
  scannerCardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 15,
  },
  logoAndStatus: {
    alignItems: 'center',
    marginBottom: 20,
  },
  statusMessage: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 5,
    marginBottom: 10,
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  modeSelector: {
    flexDirection: 'row',
    backgroundColor: '#EAEAEA',
    borderRadius: 10,
    padding: 3,
    marginBottom: 25,
    width: '100%',
  },
  modeButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  modeButtonActive: {
    backgroundColor: Colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 4,
  },
  modeButtonText: {
    color: '#666',
    fontWeight: '600',
    fontSize: 15,
  },
  modeButtonTextActive: {
    color: Colors.primary,
    fontWeight: '700',
  },
  startButtonWrapper: {
    width: '100%',
    height: 60,
    borderRadius: 15,
    shadowColor: Colors.primaryDark,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 5,
  },
  startButtonGradient: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 15,
    overflow: 'hidden',
  },
  startButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  sectionSeparator: {
    height: 1,
    backgroundColor: '#F0F0F0',
    width: '110%',
    marginVertical: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 5,
  },
  fileActionContainer: {
    width: '100%',
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  fileNameText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  analysisButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  smallButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    paddingVertical: 14,
    borderRadius: 12,
    marginHorizontal: 6,
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  smallButtonCancel: {
    borderColor: '#E53E3E',
  },
  smallButtonAnalyze: {
    borderColor: Colors.primary,
  },
  smallButtonText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '700',
  },
  smallButtonTextCancel: {
    color: '#E53E3E',
  },
  smallButtonTextAnalyze: {
    color: Colors.primary,
  },
  analyzingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 60,
  },
  loaderIcon: {
    marginRight: 12,
  },
  analyzingText: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.primary,
  },
  statusCard: {
    backgroundColor: Colors.white,
    borderRadius: 15,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 5,
  },
  statusCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 15,
  },
  statusItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
    marginLeft: 10,
    flex: 1,
  },
  statusValue: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.primaryDark,
  },
  statusValueDisconnected: {
    color: '#E53E3E',
  },
  statusSeparator: {
    height: 1,
    backgroundColor: '#F0F0F0',
    marginVertical: 4,
  },
  connectButton: {
    marginTop: 15,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.primary,
  },
  connectButtonText: {
    color: Colors.primary,
    fontWeight: '700',
    fontSize: 15,
  }
  ,
  bluetoothWarning: {
    marginTop: 12,
    color: '#B91C1C',
    textAlign: 'center',
    fontSize: 13,
  }
});
